In [ ]:
# https://www.geeksforgeeks.org/0-1-knapsack-problem-dp-10/

In [ ]:
# val = [60, 100, 120] 
# wt = [10, 20, 30] 
# W = 50

val = [10, 40, 30, 50] 
wt = [5, 4, 6, 3] 
W = 10

n = len(val) 

In [ ]:
# recursive
def knapSack(capacity, wt, val, n):
    if (n==0 or capacity==0):
        return 0
    if wt[n-1]<=capacity:
        return max(val[n-1]+knapSack(capacity-wt[n-1], wt, val, n-1),
                   knapSack(capacity, wt, val, n-1))
    elif (wt[n-1]>capacity):
        return knapSack(capacity, wt, val, n-1)

In [ ]:
knapSack(W, wt, val, n)

In [ ]:
# recursive + memoize
import numpy as np
t = -1*np.ones((n+1, W+1),dtype='int')
def knapSack(capacity, wt, val, n):
    if (n==0 or capacity==0):
        return 0
    
    if t[n, capacity] !=-1:
        return t[n, capacity]
    
    if wt[n-1]<=capacity:
        t[n-1, capacity] = max(val[n-1]+knapSack(capacity-wt[n-1], wt, val, n-1),
                               knapSack(capacity, wt, val, n-1))
        return t[n-1, capacity] 
    
    elif (wt[n-1]>capacity):
        t[n-1, capacity] = knapSack(capacity, wt, val, n-1)
        return t[n-1, capacity]

In [ ]:
knapSack(W, wt, val, n)

In [ ]:
# np.array([[0 for x in range(W+1)] for x in range(n+1)])

In [ ]:
# Bottom up
import numpy as np
def knapSack(capacity, wt, val, n):
    k = np.zeros((n+1, capacity+1),dtype='int')
    
    for i in range(n+1):
        for j in range(capacity+1):
            if (i==0 or j==0):
                k[i,j] = 0
                
            elif wt[i-1]<=j:
                k[i,j] = max(val[i-1]+k[i-1, j-wt[i-1]], k[i-1, j])
                
            else:
                k[i,j] = k[i-1, j]
    return k[n, capacity] 

In [ ]:
knapSack(W, wt, val, n)

In [46]:
# Bottom up: Knapsack algorithm
# subset sum problem
import numpy as np
def subsetSum(SUM, arr):
    n = len(arr)
    S = np.zeros((n+1, SUM+1),dtype='bool')
    S[:,0] = True
    
    for i in range(1, n+1):
        for j in range(1, SUM+1):
            if arr[i-1]<=j:
                S[i,j] = S[i-1, j-arr[i-1]] or S[i-1, j]
                
            else:
                S[i,j] = S[i-1, j]
    return S[n, SUM] 

In [47]:
arr = [2, 3, 7, 8, 10]
SUM = 11
subsetSum(SUM, arr)

True

In [48]:
# Equal Sum partition
arr = [1, 5, 11, 5]

def equalSumPartition(arr):
    if sum(arr)%2:
        return False
    else:
        result = subsetSum(int(sum(arr)/2), arr)
        
    return result
equalSumPartition(arr)

True

In [49]:
# count number of subset of a given sum
arr = [2, 3, 5, 6, 8, 10]
SUM = 10
# arr = [1, 3, 4]
# SUM = 4
S = np.zeros((len(arr)+1, SUM+1),dtype='int')
def subsetSum(SUM, arr):
    n = len(arr)
    
    S[:,0] = 1
    
    for i in range(1,n+1):
        for j in range(1,SUM+1):
            if arr[i-1]<=j:
                S[i,j] = S[i-1, j-arr[i-1]] + S[i-1, j]
                
            else:
                S[i,j] = S[i-1, j]
    return S[n, SUM] 

subsetSum(SUM, arr)

3

In [50]:
print(S)

[[1 0 0 0 0 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0 0]
 [1 0 1 1 0 1 0 0 0 0 0]
 [1 0 1 1 0 2 0 1 1 0 1]
 [1 0 1 1 0 2 1 1 2 1 1]
 [1 0 1 1 0 2 1 1 3 1 2]
 [1 0 1 1 0 2 1 1 3 1 3]]


In [80]:
# Minimum subset sum difference
arr = [1, 2, 7]

def subsetSum_(SUM, arr):
    n = len(arr)    
    S = np.zeros((len(arr)+1, SUM+1),dtype='bool')
    S[:,0] = True
    
    for i in range(1, n+1):
        for j in range(1, SUM+1):
            if arr[i-1]<=j:
                S[i,j] = S[i-1, j-arr[i-1]] or S[i-1, j]
                
            else:
                S[i,j] = S[i-1, j]
    return S[-1,:] # returning the candidate values of one partion sum

def minSubsetDifference(arr):
    RANGE = sum(arr)
    vector = subsetSum_(10, arr)
    candidates = [i for i in range(len(vector)) if vector[i]]
    minimum = RANGE
    for candidate in candidates:
        if min(minimum, RANGE-2*candidate)>0:
            minimum = min(minimum, RANGE-2*candidate)
        else:
            break
    return minimum

minSubsetDifference(arr)

4